### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by impallari** [simoncozens/silson#5]
Just a reminder to myself to send you some feedback about this font @impallari

**Comment by impallari** [comment]
Hi Simons, attached one round of feedback for the bold master "adhesion".
In the "Feedback Log.txt" file I've detailed everything I did and why I did it.
You also have the screen captures before/after, otf files before/after, and the glyph files with my edits.
Hope it helps!
[Silson Feedback - Round 01.zip](https://github.com/simoncozens/silson/files/416866/Silson.Feedback.-.Round.01.zip)

**Comment by simoncozens** [comment]
Wow! Thank you very much! It will take me some time to process all this...

**Comment by impallari** [comment]
Yes of course, take your time, no hurries.

I also want to do a "Round 2" when I get some free time.
It will be about the relation of counters to sidebearings.
Right now the counters are big and the sidebearing are small.

There are a few possible solutions:
Option 1) Increase sidebearings and keep the design as it is.
Option 2) Reduce the counters by making the design narrower.
Option 3) Reduce the counters by making the design bolder.
Option 4) A combination of options 1,2 and 3.
I want to explore those options and present the result to you, so you can see for yourself, compare and make the final decision.
